default_platform(:ios)

platform :ios do

  setup_ci(provider: "travis")

  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      in_house: false
    )

    username = ENV['USERNAME']
    personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)
   	 
    match(
      git_basic_authorization: basic_authorization_token,
      app_identifier: "com.tdk0105.shinya.helloworld-iOS",
      api_key: api_key,
      type: "appstore",
      readonly: is_ci
    )
   
    increment_build_number(xcodeproj: "helloworld_iOS.xcodeproj")

    build_app(
      scheme: "helloworld_iOS",
      export_options: {
        method: "app-store",
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
